### ISSUE TITLE
[HTTP/1.1 403 Forbidden 22ms]

### ISSUE THREAD

**Issue by HONGBAEKIM** [HONGBAEKIM/hongbooking#11]
GET
https://www.hongpage.com/static/style.css
[HTTP/1.1 403 Forbidden 22ms]

GET
https://www.hongpage.com/static/style.css
Status
403
Forbidden

**Comment by HongbaeKim** [comment]
# Ensure read and execute permissions on the directories
`chmod +rx /home/ubuntu'

'chmod +rx /home/ubuntu/hongbooking'

'chmod +rx /home/ubuntu/hongbooking/test_server_back2`


# Set read and execute permissions for the 'www-data' user on the 'static'

`chmod +rx /home/ubuntu/hongbooking/test_server_back2/static'

'chmod +r /home/ubuntu/hongbooking/test_server_back2/static/script.js'

'chmod +r /home/ubuntu/hongbooking/test_server_back2/static/style.css`
