### ISSUE TITLE
server is so slow cus code is too heavy.

### ISSUE THREAD

**Issue by HONGBAEKIM** [HONGBAEKIM/hongbooking#12]
To optimize the performance of your code, here are some suggestions:

  1.  Reduce Wait Times: In several places, you are using time.sleep() to pause execution. Instead of using fixed wait times, consider using explicit waits (WebDriverWait) with appropriate conditions. This allows your script to proceed as soon as the condition is met, rather than waiting for a fixed duration.

   2. Minimize WebDriver Initialization: Avoid initializing the WebDriver multiple times. Initialize it once and reuse it throughout the script.

    3. Optimize XPath and CSS Selectors: Make sure your XPath and CSS selectors are efficient and specific. Avoid using complex or inefficient selectors that can slow down the execution.

    4. Batch Operations: If possible, batch your operations to reduce the number of interactions with the web page. For example, instead of clicking on each slot individually, collect all the slots that match your criteria and then perform a single click operation.

    5. Optimize Exception Handling: Review your exception handling logic to ensure that it is efficient and handles only the necessary exceptions. Catching too broad exceptions or unnecessary exceptions can impact performance.

    6. Use Headless Mode: You are already using headless mode for Firefox. This can significantly improve performance by avoiding the overhead of rendering the browser window.

    7. Profile and Optimize: Profile your code to identify performance bottlenecks. Use profiling tools to understand where most of the time is spent and optimize those areas accordingly.

    8. Parallelize Tasks: If your script performs independent tasks, consider parallelizing them using threads or asynchronous programming to leverage multiple CPU cores and improve overall throughput.

**Comment by HongbaeKim** [comment]
deleted WebDriverWait functions.
