### ISSUE TITLE
Shortage memory of AWS EC2 server

### ISSUE THREAD

**Issue by HONGBAEKIM** [HONGBAEKIM/hongbooking#18]
when I run my program in server, it took so long and stoped.

i think this is shortage or memory problem. because AWS EC2 freetier has 30GB SSD and 1GB memory.

1. Pay additional money to use auto-scale
2. Add SWAP memory

**Comment by HongbaeKim** [comment]
I chose number 2. Add SWAP memory.

Nomally, SSD(Solid State Drive) speed is 450MB/s
but, RAM memory speed is 12800MB/s

So Let's set up SWAP space in ubuntu.

0) Allocate SWAP memory
`sudo dd if=/dev/zero of=/swapfile bs=128M count=16`

1)change permission
`sudo chmod 600 /swapfile`

2)MAke SWAP Space
`sudo mkswap /swapfile`

3)Add SWAP file to SWAP space
`sudo swapon /swapfile`

4)Check swap space
`sudo swapon -s`

5)To automatic activation
go here
`sudo vi /etc/fstab` 

and add below 
`/swapfile swap swap defualts 0 0 `


6) Check current memory
`free -h`
