### ISSUE TITLE
Setup AWS E2C server in terminal

### ISSUE THREAD

**Issue by HONGBAEKIM** [HONGBAEKIM/hongbooking#19]
and server has been broken. OHHH...

Ok Let's make new server (AWS EC2 Ubuntu free tier)

**Comment by HongbaeKim** [comment]
after set up new server

setup swapfile to use 2GB RAM MEMORY
#18 

Package management system checks the repositories configured on the system for any update.
`sudo apt update`

Upgrade installed packages to their latest available versions
`sudo apt upgrade`

Install the Python 3 package manager (pip) for managing Python packages and dependencies
`sudo apt install python3-pip`

Selenium Python package, which allows for automated web browser testing and web scraping
`pip install selenium`

Undetectable ChromeDriver for Selenium automation, useful for bypassing bot detection mechanisms.
'pip install undetected-chromedriver'

Pyotp provides functionality for generating and validating one-time password (OTP)
`sudo pip3 install pyotp`


Google Chrome on Ubuntu using the command line 
0)Add Google Chrome Repository:
`wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -`

1)Set Up Repository
`sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'`

2)sudo apt update
`sudo apt update`

3)Install Google Chrome
`sudo apt install google-chrome-stable`


Install pyinstaller which 
0)make from .py to dist file
`pip install pyinstaller`

1)find where It was installed
`find /home/ubuntu/.local -name pyinstaller`

2)run and make dist file
`~/.local/bin/pyinstaller hongbook18.py`



Install Flask which a lightweight web application framework for Python
`pip3 install Flask`

flask_cors is an extension for Flask that provides Cross-Origin Resource Sharing (CORS) support, which allows you to make requests from one domain to another domain in web applications.
`pip3 install flask-cors`

flask_socketio is an extension for Flask that adds support for handling WebSocket connections in your application.
`pip3 install flask-socketio`

install nginx
Nginx (pronounced as "Engine-X") is a powerful, high-performance web server, reverse proxy, and email (IMAP/POP3) proxy, known for its stability, rich feature set, simple configuration, and low resource consumption. 
`sudo apt-get install nginx
sudo service nginx start`
