### ISSUE TITLE
A licensing system

### ISSUE THREAD

**Issue by HONGBAEKIM** [HONGBAEKIM/hongbooking#22]
A licensing system for your software that relies on cryptographic keys to enable or disable functionality based on user purchases or permissions.

A common approach involves using a combination of public-key cryptography (for validating the integrity and origin of the license key) and a time-based check (to enforce the license duration).

1.Initial Setup:

Users download your program along with the initial private.pem and public.pem files.
These files are essential for running your program.

2.Running the Program:

Users run your program on their systems.
Your program checks the validity of the private.pem file.
If the private.pem file is valid (i.e., its expiration time hasn't passed), the program continues to run normally.
If the private.pem file has expired, the program prompts the user to visit your website to download updated private.pem and public.pem files.

3.Updating Private and Public Keys:

Users visit your website to download the updated private.pem and public.pem files.
These updated files have new expiration times, typically one hour from the time of download.
Users replace the old private.pem and public.pem files with the new ones on their systems.

4.Continued Use:

Users can now run your program again with the updated private.pem and public.pem files.
The program checks the validity of the new private.pem file and continues to run if it's valid.

5.Repeat Process:

This process repeats every time the private.pem file expires, ensuring that users always have access to valid private and public keys.

**Comment by HongbaeKim** [comment]
generate an RSA key pair (private key and corresponding public key) 
`openssl genrsa -out private.pem 2048`
`openssl rsa -in private.pem -outform PEM -pubout -out public.pem`


generate a self-signed X.509 certificate using OpenSSL
`openssl req -new -x509 -days 365 -nodes -out public.pem -keyout private.pem`

**Comment by HongbaeKim** [comment]
This is a future task.
