### ISSUE TITLE
Password Security

### ISSUE THREAD

**Issue by HONGBAEKIM** [HONGBAEKIM/hongbooking#4]
Because I decided to use the --headless option, I also need to manage the security of users' passwords.

However, transferring passwords from the Hongbook homepage to the 42 login page introduces security concerns. 

I am currently figuring out how to handle it

**Comment by HongbaeKim** [comment]
I have made webpage (www.hongpage.com) to HTTPS for security reason.

Let's Encrypt is a widely used and free certificate authority, and securing your website with HTTPS
https://letsencrypt.org/
